openapi: 3.0.0
info:
  title: Niceday REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.2.0
servers:
- url: /
paths:
  /messages:
    post:
      tags:
      - messages
      summary: Send a text message
      operationId: sendTextMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        "200":
          description: Success
      x-swagger-router-controller: Messages
  /userdata/{userId}:
    get:
      summary: Get user data by ID
      operationId: getUserData
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Integer ID of the user whose data is desired
          example: 38527
      responses:
        "200":
          description: Success
      x-swagger-router-controller: UserData
  /usertrackers/smoking/{userId}:
    get:
      summary: Get smoking tracker data for specific user
      operationId: getSmokingTrackerData
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Integer ID of the user whose data is desired
          example: 38527
        - in: query
          name: startTime
          schema:
            type: string
            format: date-time
          required: true
          description: The start of the time range for which to get data
          example: "2021-01-13T09:12:28Z"
        - in: query
          name: endTime
          schema:
            type: string
            format: date-time
          required: true
          description: The end of the time range for which to get data
          example: "2022-02-15T09:12:28Z"
      responses:
        "200":
          description: Succes
          content:
            application/json:
              schema:
                description: List of smoking tracker entries
                type: array
                items:
                  $ref: '#/components/schemas/SmokingTrackerEntry'
      x-swagger-router-controller: UserTrackers
  /usertrackers/statuses:
    post:
      summary: Enable or disable trackers for a user
      operationId: setUserTrackerStatuses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserTrackerStatusesInput'
      responses:
        "200":
          description: Success
      x-swagger-router-controller: UserTrackers

components:
  schemas:
    Message:
      required:
      - recipient_id
      - text
      type: object
      properties:
        recipient_id:
          type: integer
          description: ID of the user we want to send message to
          example: 38527
        text:
          type: string
          description: Message to send
          example: Hello World
      description: A Message to Send.
    SmokingTrackerEntry:
      type: object
      properties:
        id:
          type: string
          description: uid of tracker entry
          example: '620381d1af7a92028c330734'
        userId:
          type: integer
          description: id of user
          example: 38527
        startTime: 
          type: string
          example: '2022-02-09T08:56:44.349Z'
        endTime: 
          type: string
          example: '2022-02-09T08:56:44.349Z'
        sensorName:
          type: string
          example: 'measure_cigarettes'
        sourceName: 
          type: string
          example: 'goalie_2'
        version: 
          type: integer
          example: 2
        value:
          type: object
          properties:
            quantity:
              type: integer
              description: Number of cigarettes in entry
              example: 1
        createdAt: 
          type: string
          example: '2022-02-09T08:56:49.628Z'
        createdBy: 
          type: integer
          example: 38527
        updatedAt:
          type: string
          example: '2022-02-09T08:56:49.628Z'
        updatedBy: 
          type: integer
          example: 38527

    UserTrackerStatusesInput:
      description: Input for setting user tracker statuses
      required:
      - userId
      - trackerStatuses
      type: object
      properties:
        userId:
          type: integer
          description: ID of the user we want to set tracker statuses for
          example: 38527
        trackerStatuses:
          type: array
          description: List of tracker statuses
          items:
            $ref: '#/components/schemas/TrackerStatus'
    TrackerStatus:
      description: Status for a tracker
      required:
        - trackerId
        - isEnabled
      type: object
      properties:
        trackerId:
          type: integer
          description: >
            ID of the the tracker (see https://github.com/senseobservationsystems/goalie-js/issues/840
            on how to get tracker IDs, for example: cigarette counter has id=1)
          example: 1
        isEnabled:
          type: boolean
          description: Whether the tracker should be enabled
          example: true

