#!/bin/bash
if [[ ! -d "./build/goalie-js" ]]; then
    git clone https://github.com/PerfectFit-project/goalie-js.git --single-branch --branch perfectfit-patch ./build/goalie-js || exit 2
fi

cd ./build/goalie-js
yarn install
tsc --sourceMap -p .
