name: Build and publish the niceday broker and api images to ghcr.io

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - issue172_design_deployment_process

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  publish_niceday_broker:
    
    uses: ./.github/workflows/ghcr_build_and_push_with_goaliejs.yml
    with:
      imagename: niceday_broker
      context: niceday-broker/
    secrets:
      goaliejskey: ${{ secrets.GOALIEJS_PRIVATE_PULL_KEY }}
  publish_niceday_api:
    uses: ./.github/workflows/ghcr_build_and_push_with_goaliejs.yml
    with:
      imagename: niceday_api
      context: niceday-api/
    secrets:
      goaliejskey: ${{ secrets.GOALIEJS_PRIVATE_PULL_KEY }}
